repositories:
- name: helm-remote
  url: https://kubernetes-charts.storage.googleapis.com/

releases:
- name: prometheus-operator
  namespace: monitoring
  chart: helm-remote/prometheus-operator
  cleanupOnFail: true
  labels:
    chart: "prometheus-operator"
    repo: "helm-remote"
    component: "prometheus-operator"
    namespace: "monitoring"
    vendor: "kubernetes"
  values:
    - prometheus-node-exporter:
      grafana:
        admin:
          existingSecret: grafana-secret
        service:
          port: 3000
        sidecar:
          dashboards:
            enabled: true
            # label that the configmaps with dashboards are marked with
            label: grafana_dashboard
            # folder in the pod that should hold the collected dashboards
            folder: /tmp/dashboards
          datasources:
            enabled: true
            # label that the configmaps with datasources are marked with
            label: grafana_datasource
