---
bases:
  - ../common/environments.yaml
---
repositories:
- name: helm-remote
  url: {{ .Environment.Values.helm.remote.url }}

releases:
- name: prometheus
  namespace: monitoring
  chart: helm-remote/prometheus
  values:
    - rbac:
        create: true
      kubeStateMetrics:
        image:
          repository: {{ .Environment.Values.docker.proxy }}quay.io/coreos/kube-state-metrics
      alertmanager:
        image:
          repository: {{ .Environment.Values.docker.proxy }}prom/alertmanager
      configmapReload:
        image:
          repository: {{ .Environment.Values.docker.proxy }}jimmidyson/configmap-reload
      server:
        service:
          servicePort: 9090
          type: LoadBalancer
